spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/itzixi-pay?serverTimezone=UTC&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: 123456
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 3000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 20
      minimum-idle: 2
      pool-name: HikariCP
mybatis-plus:
  type-aliases-package: com.moxuan.payment
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#分页设置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: false #pageSize=0 返回所有
  params: count=countSql
# redis
  redis:
    database: 0
    host: 127.0.0.1
    jedis:
      pool:
        # 连接池最大jedis实例个数，如果赋值为-1，则表示不限制；pool如果已经全部分配，则状态变为exhausted(耗尽)。
        max-active: 210
        # 连接池中的最大空闲连接，默认值也是8
        max-idle: 10
        # 可用连接的最大等待时间，单位毫秒，默认值为-1，表示永不超时。如果超时，则直接抛出JedisConnectionException
        max-wait: 10000
        #连接池中的最小空闲连接，默认值也是0
        min-idle: 3
    password: ''
    port: 6379
    # 连接超时时间，单位 ms（毫秒）
    timeout: 3200



